/*
 * This file is part of the Emulation-as-a-Service framework.
 *
 * The Emulation-as-a-Service framework is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * The Emulation-as-a-Service framework is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Emulation-as-a-Software framework.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package de.bwl.bwfla.common.jaxwsstubs.imagearchive;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-08-08T17:29:21.727+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ImageArchiveWSService", 
                  wsdlLocation = "http://132.230.4.10:8080/image-archive/ImageArchiveWS?wsdl",
                  targetNamespace = "http://imagearchive.bwfla.bwl.de/") 
public class ImageArchiveWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://imagearchive.bwfla.bwl.de/", "ImageArchiveWSService");
    public final static QName ImageArchiveWSPort = new QName("http://imagearchive.bwfla.bwl.de/", "ImageArchiveWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://132.230.4.10:8080/image-archive/ImageArchiveWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImageArchiveWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://132.230.4.10:8080/image-archive/ImageArchiveWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImageArchiveWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImageArchiveWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageArchiveWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImageArchiveWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImageArchiveWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImageArchiveWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ImageArchiveWSRemote
     */
    @WebEndpoint(name = "ImageArchiveWSPort")
    public ImageArchiveWSRemote getImageArchiveWSPort() {
        return super.getPort(ImageArchiveWSPort, ImageArchiveWSRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageArchiveWSRemote
     */
    @WebEndpoint(name = "ImageArchiveWSPort")
    public ImageArchiveWSRemote getImageArchiveWSPort(WebServiceFeature... features) {
        return super.getPort(ImageArchiveWSPort, ImageArchiveWSRemote.class, features);
    }

}
