package de.bwl.bwfla.common.jaxwsstubs.softwarearchive;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-04-20T18:21:30.288+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "SoftwareArchiveWSService", 
                  wsdlLocation = "http://localhost:8080/softwarearchive/SoftwareArchiveWS?wsdl",
                  targetNamespace = "http://softwarearchive.bwfla.bwl.de/") 
public class SoftwareArchiveWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://softwarearchive.bwfla.bwl.de/", "SoftwareArchiveWSService");
    public final static QName SoftwareArchiveWSPort = new QName("http://softwarearchive.bwfla.bwl.de/", "SoftwareArchiveWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/softwarearchive/SoftwareArchiveWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoftwareArchiveWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/softwarearchive/SoftwareArchiveWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoftwareArchiveWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoftwareArchiveWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoftwareArchiveWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoftwareArchiveWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoftwareArchiveWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoftwareArchiveWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SoftwareArchiveWSRemote
     */
    @WebEndpoint(name = "SoftwareArchiveWSPort")
    public SoftwareArchiveWSRemote getSoftwareArchiveWSPort() {
        return super.getPort(SoftwareArchiveWSPort, SoftwareArchiveWSRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoftwareArchiveWSRemote
     */
    @WebEndpoint(name = "SoftwareArchiveWSPort")
    public SoftwareArchiveWSRemote getSoftwareArchiveWSPort(WebServiceFeature... features) {
        return super.getPort(SoftwareArchiveWSPort, SoftwareArchiveWSRemote.class, features);
    }

}
