/*
 * This file is part of the Emulation-as-a-Service framework.
 *
 * The Emulation-as-a-Service framework is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * The Emulation-as-a-Service framework is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Emulation-as-a-Software framework.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package de.bwl.bwfla.api.cluster;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-09-12T18:40:44.778+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://bwfla.bwl.de/api/cluster/", name = "ResourceAllocatorWS")
public interface ResourceAllocatorWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInternalSession", targetNamespace = "http://bwfla.bwl.de/api/cluster/", className = "de.bwl.bwfla.api.cluster.GetInternalSession")
    @WebMethod
    @ResponseWrapper(localName = "getInternalSessionResponse", targetNamespace = "http://bwfla.bwl.de/api/cluster/", className = "de.bwl.bwfla.api.cluster.GetInternalSessionResponse")
    public de.bwl.bwfla.api.cluster.EmuSession getInternalSession(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "allocate", targetNamespace = "http://bwfla.bwl.de/api/cluster/", className = "de.bwl.bwfla.api.cluster.Allocate")
    @WebMethod
    @ResponseWrapper(localName = "allocateResponse", targetNamespace = "http://bwfla.bwl.de/api/cluster/", className = "de.bwl.bwfla.api.cluster.AllocateResponse")
    public java.lang.String allocate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "release", targetNamespace = "http://bwfla.bwl.de/api/cluster/", className = "de.bwl.bwfla.api.cluster.Release")
    @WebMethod
    @ResponseWrapper(localName = "releaseResponse", targetNamespace = "http://bwfla.bwl.de/api/cluster/", className = "de.bwl.bwfla.api.cluster.ReleaseResponse")
    public void release(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
