/*
 * This file is part of the Emulation-as-a-Service framework.
 *
 * The Emulation-as-a-Service framework is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * The Emulation-as-a-Service framework is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Emulation-as-a-Software framework.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package de.bwl.bwfla.api.cluster;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-09-12T18:40:44.820+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ResourceAllocatorWSService", 
                  wsdlLocation = "http://localhost:8080/eaas-ejb/ResourceAllocatorWS?wsdl",
                  targetNamespace = "http://bwfla.bwl.de/api/cluster/") 
public class ResourceAllocatorWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bwfla.bwl.de/api/cluster/", "ResourceAllocatorWSService");
    public final static QName ResourceAllocatorWSPort = new QName("http://bwfla.bwl.de/api/cluster/", "ResourceAllocatorWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/eaas-ejb/ResourceAllocatorWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ResourceAllocatorWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/eaas-ejb/ResourceAllocatorWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ResourceAllocatorWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResourceAllocatorWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceAllocatorWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ResourceAllocatorWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ResourceAllocatorWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ResourceAllocatorWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ResourceAllocatorWS
     */
    @WebEndpoint(name = "ResourceAllocatorWSPort")
    public ResourceAllocatorWS getResourceAllocatorWSPort() {
        return super.getPort(ResourceAllocatorWSPort, ResourceAllocatorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResourceAllocatorWS
     */
    @WebEndpoint(name = "ResourceAllocatorWSPort")
    public ResourceAllocatorWS getResourceAllocatorWSPort(WebServiceFeature... features) {
        return super.getPort(ResourceAllocatorWSPort, ResourceAllocatorWS.class, features);
    }

}
