/*
 * This file is part of the Emulation-as-a-Service framework.
 *
 * The Emulation-as-a-Service framework is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * The Emulation-as-a-Service framework is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Emulation-as-a-Software framework.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package de.bwl.bwfla.common.jaxwsstubs.objectarchive;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-06-25T11:27:52.706+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://objectarchive.bwfla.bwl.de/", name = "DigitalObjectArchive")
public interface DigitalObjectArchive {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getObjectReference", targetNamespace = "http://objectarchive.bwfla.bwl.de/", className = "de.bwl.bwfla.objectarchive.GetObjectReference")
    @WebMethod
    @ResponseWrapper(localName = "getObjectReferenceResponse", targetNamespace = "http://objectarchive.bwfla.bwl.de/", className = "de.bwl.bwfla.objectarchive.GetObjectReferenceResponse")
    public java.lang.String getObjectReference(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://objectarchive.bwfla.bwl.de/", className = "de.bwl.bwfla.objectarchive.GetName")
    @WebMethod
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://objectarchive.bwfla.bwl.de/", className = "de.bwl.bwfla.objectarchive.GetNameResponse")
    public java.lang.String getName();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getObjectList", targetNamespace = "http://objectarchive.bwfla.bwl.de/", className = "de.bwl.bwfla.objectarchive.GetObjectList")
    @WebMethod
    @ResponseWrapper(localName = "getObjectListResponse", targetNamespace = "http://objectarchive.bwfla.bwl.de/", className = "de.bwl.bwfla.objectarchive.GetObjectListResponse")
    public java.util.List<java.lang.String> getObjectList();
}
