/*
 * This file is part of the Emulation-as-a-Service framework.
 *
 * The Emulation-as-a-Service framework is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * The Emulation-as-a-Service framework is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Emulation-as-a-Software framework.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package de.bwl.bwfla.common.jaxwsstubs.objectarchive;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-06-25T11:27:52.749+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "DigitalObjectArchiveService", 
                  wsdlLocation = "http://localhost:8080/objectarchive-ejb/DigitalObjectArchive?wsdl",
                  targetNamespace = "http://objectarchive.bwfla.bwl.de/") 
public class DigitalObjectArchiveService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://objectarchive.bwfla.bwl.de/", "DigitalObjectArchiveService");
    public final static QName DigitalObjectArchivePort = new QName("http://objectarchive.bwfla.bwl.de/", "DigitalObjectArchivePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/objectarchive-ejb/DigitalObjectArchive?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DigitalObjectArchiveService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/objectarchive-ejb/DigitalObjectArchive?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DigitalObjectArchiveService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DigitalObjectArchiveService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DigitalObjectArchiveService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DigitalObjectArchiveService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DigitalObjectArchiveService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DigitalObjectArchiveService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DigitalObjectArchive
     */
    @WebEndpoint(name = "DigitalObjectArchivePort")
    public DigitalObjectArchive getDigitalObjectArchivePort() {
        return super.getPort(DigitalObjectArchivePort, DigitalObjectArchive.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigitalObjectArchive
     */
    @WebEndpoint(name = "DigitalObjectArchivePort")
    public DigitalObjectArchive getDigitalObjectArchivePort(WebServiceFeature... features) {
        return super.getPort(DigitalObjectArchivePort, DigitalObjectArchive.class, features);
    }

}
