/*
 * This file is part of the Emulation-as-a-Service framework.
 *
 * The Emulation-as-a-Service framework is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * The Emulation-as-a-Service framework is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Emulation-as-a-Software framework.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package de.bwl.bwfla.common.jaxwsstubs.workflowsapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-26T16:23:04.060+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://api.external.bwfla.bwl.de/", name = "AccessAPI")
public interface AccessAPI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "access", targetNamespace = "http://api.external.bwfla.bwl.de/", className = "de.bwl.bwfla.common.jaxwsstubs.workflowsapi.Access")
    @WebMethod
    @ResponseWrapper(localName = "accessResponse", targetNamespace = "http://api.external.bwfla.bwl.de/", className = "de.bwl.bwfla.common.jaxwsstubs.workflowsapi.AccessResponse")
    public de.bwl.bwfla.common.jaxwsstubs.workflowsapi.AccessResult access(
        @WebParam(name = "arg0", targetNamespace = "")
        javax.activation.DataHandler arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
